import { Routes } from '@angular/router';
import { Landing } from '../landing/landing';
import { Home } from '../home/home';
import { UserHome } from '../user-home/user-home';
import { OrgHome } from '../org-home/org-home';
import { DriverHome } from '../driver-home/driver-home';
import { Login } from '../login/login';
import { Register } from '../register/register';
import { UserAccountManagement } from '../user-manage-account/user-manage-account';
import { OrgAccountManagement } from '../org-manage-account/org-manage-account';
import { DriverAccountManagement } from '../driver-manage-account/driver-manage-account';
import { UserOrderHistory } from '../user-order-history/user-order-history';
import { OrgOrderHistory } from '../org-order-history/org-order-history';
import { DriverOrderHistory } from '../driver-order-history/driver-order-history';
import { InventoryManagement } from '../inventory-management/inventory-management';
import { Deliveries } from '../deliveries/deliveries';
import { Donate } from './get-involved/donate/donate';
import { Restaurants } from './find-resources/restaurants/restaurants';
import { Community } from './find-resources/community/community';
import { Events } from './news-media/events/events';
import { Blog } from './news-media/blog/blog';
import { Mission } from './about-us/mission/mission';
import { Contact } from './about-us/contact/contact';

export const routes: Routes = [
  { path: '', component: Landing },
  { path: 'home', component: Home },
  //{ path: 'user-home', component: UserHome },
  { path: 'org-home', component: OrgHome },
  { path: 'driver-home', component: DriverHome },
  { path: 'login', component: Login },
  { path: 'register', component: Register },
  { path: 'user-account', component: UserAccountManagement },
  { path: 'org-account', component: OrgAccountManagement },
  { path: 'driver-account', component: DriverAccountManagement },
  { path: 'user-history', component: UserOrderHistory },
  { path: 'org-history', component: OrgOrderHistory },
  { path: 'driver-history', component: DriverOrderHistory },
  { path: 'inventory', component: InventoryManagement },
  { path: 'deliveries', component: Deliveries },
  { path: 'donate', component: Donate },
  { path: 'restaurants', component: Restaurants },
  { path: 'community', component: Community },
  { path: 'events', component: Events },
  { path: 'blog', component: Blog },
  { path: 'mission', component: Mission },
  { path: 'contact', component: Contact }
];
