# frontend/Dockerfile.dev
FROM node:22-alpine
WORKDIR /app
COPY frontend/web/package*.json ./
RUN npm ci --legacy-peer-deps
#COPY frontend/web/ ./
# Add this line:
COPY frontend/proxy.conf.json ./proxy.conf.json
EXPOSE 4200
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--proxy-config", "/app/proxy.conf.json"]
